### ISSUE TITLE
There's no actual instructions or a demo scene for this code

### ISSUE THREAD

**Issue by samvila** [SIsilicon/Godot-Lens-Flare-Plugin#1]
As the subject says it lacks documentation or even a demo to see how this works.

**Comment by samvila** [comment]
Also I'm getting an error activating the plugin:

Unable to load addon script from path: 'res://addons/SIsilicon.vfx.lens flare/lens-flare-plugin.gd' Base type is not EditorPlugin.

**Comment by SIsilicon** [comment]
I will look into it right away.
And I shall also create a demo scene.

**Comment by samvila** [comment]
Awesome. I was finally being able to play with this addon but I had to fix some script files and other stuff manually. After that it looks very good, kudos!

By the way, you might want to have a look to this project even if it's just for reference:

http://codeofart.com/flares-wizard/

It's highly customizable, I know it's not for Godot but you might get some inspiration from that one.

**Comment by SIsilicon** [comment]
I'm glad to here you can use it. And thank you for giving me an informative link.

Edit: The link's broken.
