### ISSUE TITLE
The path is broken

### ISSUE THREAD

**Issue by yaelatletl** [SIsilicon/Godot-Lens-Flare-Plugin#2]
Your directory
"addons/SIsilicon.vfx.lens flare/"
is referenced in files as "addons/SIsilicon.vfx.lensflare/"

**Comment by SIsilicon** [comment]
Can you point to the files in question please?

**Comment by SIsilicon** [comment]
*3 minutes later*
After checking the files(including the .tscn ones), they seem to be referencing the path with the space between lens and flare.

So I really don't know which file you are talking about.

**Comment by yaelatletl** [comment]
The file provided in the Asset Library 
https://godotengine.org/asset-library/asset/198 
Hit the Download button, the file you get has that issue

**Comment by SIsilicon** [comment]
Ok I see the problem now. The commit on the asset store is outdated. The repository itself however should be fine. For now download directly from the repository until further notice.

**Comment by SIsilicon** [comment]
Ok so the asset store download finally got updated.
