### ISSUE TITLE
Strange shading on walls

### ISSUE THREAD

**Issue by yaelatletl** [SIsilicon/Godot-Lens-Flare-Plugin#3]
https://imgur.com/a/VoP8ZFc
That darker shading just appears when using the flare lens effect.

**Comment by SIsilicon** [comment]
Can you send me that project so that I can see what is going on? I am not getting much information from that picture.

**Comment by yaelatletl** [comment]
I'll be uploading the project to a repo soon, I'll comment again when it's uploaded
Edit: The files from the Godot Asset Library seem to be outdated, I'll try with the most recent ones first

**Comment by yaelatletl** [comment]
Nevermind, it was a mistake on my end. Great vfx.
