### ISSUE TITLE
Any hints on how it actually works?

### ISSUE THREAD

**Issue by Zylann** [SIsilicon/Godot-Lens-Flare-Plugin#4]
I installed the plugin (excluding everything that is not under `addons/` because I dont want to clutter my project), added the `LensFlare` to my scene, and nothing shows up in editor. When I play the game, I see no lens flare either.

![image](https://user-images.githubusercontent.com/1311555/95690226-0ea98c00-0c0e-11eb-90f9-fd8e77a4d4d4.png)

Note: I add my directional light and camera at runtime, if case it matters. I wonder how the plugin knows where the sun is, there is no code searching for it and no parameter as far as I can see. It also produces no errors so I have no idea if I'm missing something important.

If I create an empty project, install the plugin without excluding anything and open the `LensFlare.tscn` demo scene, I see something.
But if I just create an empty new scene and create a `LensFlare`, nothing shows up as well, so I wonder what's required to make this work?

Best I could get so far doesnt look good
![image](https://user-images.githubusercontent.com/1311555/95690586-c770ca80-0c10-11eb-9936-480c1e06ed08.png)

**Comment by SIsilicon** [comment]
Hey Zylann! You see, here's the thing about this plugin: It's procedural. It doesn't use any light nodes to calculate the effect. It works like bloom. It takes any bright points of the scene to make lens flares out of.
Notice how in the demo there is not a single directional light.

**Comment by SIsilicon** [comment]
To make it work in your case, you'd have to make a bright point in space (The sun), and the plugin will take care of the rest.
I'll update the README to explain how the plugin works.

**Comment by SIsilicon** [comment]
If you need a different approach to this, like texture based, I don't have a solution for that one right now. I've always thought of making a texture version of this plugin, but I never got around to actually doing that yet.

**Comment by Zylann** [comment]
I eventually figured out that I needed to adjust the bright point and more importantly, the lens blur, because my sun is a sphere so it cuts off hard compared to a sun from a panorama texture.

![image](https://user-images.githubusercontent.com/1311555/95690868-b2953680-0c12-11eb-8149-f21cf8bbd4af.png)

**Comment by SIsilicon** [comment]
I'm glad you figured it out! 😃
So, is there anything you can tell me about that you think would make this plugin better? Just some user feedback.

**Comment by Zylann** [comment]
- Maybe a quick note about how the plugin works (the fact it only uses the brightness from the render)
- Wrap demo contents under a demo folder?
- Maybe an option to control the strength of streaks?

Otherwise, past understanding the few details I bumped on, it works pretty well :)

**Comment by SIsilicon** [comment]
Thanks! I'll update it later. I hope the plugin proves useful to you. 😉

**Comment by SIsilicon** [comment]
Done!
