### ISSUE TITLE
Flare strength becomes weaker if left to default

### ISSUE THREAD

**Issue by Zylann** [SIsilicon/Godot-Lens-Flare-Plugin#5]
In Godot 3.2.3, I tweaked the lens flare settings while leaving the strength to 10.0 (its default value) to obtain this: https://github.com/SIsilicon/Godot-Lens-Flare-Plugin/issues/4#issuecomment-706771922

Then I closed the project, and reopened it. I didnt touch anything, and this is how it looked *when playing the game*:
![image](https://user-images.githubusercontent.com/1311555/95696902-d9646480-0c34-11eb-9e57-d0a2af2b21b9.png)

It looks a lot fainter. So I increase strength so `10.0001`, and this is the result:
![image](https://user-images.githubusercontent.com/1311555/95696936-f6993300-0c34-11eb-9668-fa30b4589798.png)

Then back to `10`:
![image](https://user-images.githubusercontent.com/1311555/95696951-09136c80-0c35-11eb-97b6-3b1f16452dc4.png)

Then closed Godot, and reopened, which made it go back to this:
![image](https://user-images.githubusercontent.com/1311555/95697064-76270200-0c35-11eb-83d8-9385a0c8c0bd.png)

I know Godot is not saving default values (and because of this, not setting them), which means, a value of 10 will make the setter not called, despite the variable being `10`. In the material, the initial value is `0.294` so it's actually gonna default to that, due to the setter not being called.
To fix this you either need to constantly keep default values the same as the material's initial values, or trigger all setters in ready.

Note: this applies to all parameters, not just strength.

**Comment by SIsilicon** [comment]
I hate it when that happens!
I can't seem to find the best way to keep values the way they are! I'll look into this tomorrow.

**Comment by SIsilicon** [comment]
Alright, it should be fixed in the master branch now. 🙂

**Comment by SIsilicon** [comment]
@Zylann Let me know if the issue's fixed.

**Comment by SIsilicon** [comment]
I'm just going to assume it's all good now.
